import { StyleSheet } from "react-native";
import { C, F, R } from "@/lib/theme";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: C.surface,
    borderRadius: R,
    borderWidth: 1,
    borderColor: C.border,
    padding: 14,
    gap: 12,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  textColumn: { flex: 1, gap: 2 },
  username: { fontFamily: F.bodyBold, fontSize: 15, color: C.text },
  displayName: { fontFamily: F.monoRegular, fontSize: 11, color: C.muted },
  badges: { flexDirection: "row", gap: 6 },
  badge: { paddingHorizontal: 8, paddingVertical: 4 },
  adminBadge: { backgroundColor: C.tertiary },
  adminBadgeText: { fontFamily: F.mono, fontSize: 9, color: C.onTertiary, letterSpacing: 1 },
  bannedBadge: { backgroundColor: C.errorContainer, borderWidth: 1, borderColor: C.errorBorder },
  bannedBadgeText: { fontFamily: F.mono, fontSize: 9, color: C.error, letterSpacing: 1 },
  buttonRow: { flexDirection: "row", gap: 10 },
  historyBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: C.borderVariant,
    paddingVertical: 12,
    alignItems: "center",
  },
  historyBtnText: { fontFamily: F.mono, fontSize: 11, color: C.muted, letterSpacing: 1 },
  banBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: C.errorBorder,
    backgroundColor: C.errorContainer,
    paddingVertical: 12,
    alignItems: "center",
  },
  banText: { fontFamily: F.mono, fontSize: 12, color: C.error, letterSpacing: 1 },
  unbanBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: C.primary,
    backgroundColor: C.primary,
    paddingVertical: 12,
    alignItems: "center",
  },
  unbanText: { fontFamily: F.mono, fontSize: 12, color: C.onPrimary, letterSpacing: 1 },
  historySection: {
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: C.borderVariant,
  },
  historyEmpty: {
    fontFamily: F.body,
    fontSize: 12,
    color: C.muted,
    fontStyle: "italic",
  },
  historyRow: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  historyText: { flex: 1, gap: 2 },
  historyReason: { fontFamily: F.body, fontSize: 13, color: C.textVariant },
  historyMeta: { fontFamily: F.monoRegular, fontSize: 10, color: C.muted, letterSpacing: 0.3 },
});
