import { StyleSheet } from "react-native";
import { C, F, TAPE } from "@/lib/theme";

export const styles = StyleSheet.create({
  loading: { marginVertical: 12 },
  section: { paddingTop: 14, borderTopWidth: 1, borderTopColor: C.borderVariant, gap: 10 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionLabel: { fontFamily: F.mono, fontSize: 10, color: C.muted, letterSpacing: 2 },
  editLink: { fontFamily: F.mono, fontSize: 11, letterSpacing: 0.5 },
  hoursRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  hoursText: { fontFamily: F.body, fontSize: 13, color: C.textVariant, flex: 1 },
  weekList: { gap: 4, paddingLeft: 23 },
  weekRow: { flexDirection: "row", justifyContent: "space-between" },
  weekDay: { fontFamily: F.body, fontSize: 12, color: C.muted },
  weekHours: { fontFamily: F.monoRegular, fontSize: 12, color: C.textVariant },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  chipText: { fontFamily: F.mono, fontSize: 10, color: C.muted, letterSpacing: 0.5 },
  facilityChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: C.primary,
    transform: [{ rotate: TAPE.rotatePrimary }],
  },
  facilityChipText: { fontFamily: F.mono, fontSize: 10, color: C.onPrimary, letterSpacing: 0.5 },
  parkingChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: C.tertiary,
    transform: [{ rotate: TAPE.rotateTertiary }],
  },
  parkingChipText: { fontFamily: F.body, fontSize: 13, color: C.onTertiary },
  badgeOn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: C.secondary,
    transform: [{ rotate: TAPE.rotateSecondary }],
  },
  badgeOnText: { fontFamily: F.mono, fontSize: 10, color: C.onSecondary, letterSpacing: 0.5 },
  badgeOff: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: C.borderVariant,
    backgroundColor: C.surface,
  },
  emptyText: {
    fontFamily: F.body,
    fontSize: 13,
    color: C.muted,
    fontStyle: "italic",
  },
});
